import { describe, expect, it } from 'vitest'
import { withFrenchRegimes, withoutRecommendation } from '@/lib/macro-report'

// The daily macro report is generated by a model and ends with a section
// « 4. Biais recommandé » that reads as an investment recommendation
// (« NEUTRE à légèrement SHORT sur ETH et SOL »), on a site whose home says
// « Aucune recommandation d'achat ou de vente » (audit 2026-09-25, P0-1). The
// generator is upstream (apex, VPS): the site strips the section at render time,
// whatever the generator writes tomorrow.

const REPORT = [
  '# Analyse Macro APEX — 2026-09-25',
  '',
  '> Générée le 2026-09-25 07:00 UTC',
  '',
  '## 1. Contexte macro global',
  '',
  'Le score global tourne autour de **+12.5**.',
  '',
  '## 2. Implications pour BTC/ETH/SOL',
  '',
  'Les funding rates positifs mais modestes.',
  '',
  '## 3. Risques à surveiller',
  '',
  'Le hack Bitget est le risque dominant.',
  '',
  '## 4. Biais recommandé',
  '',
  '> NEUTRE à légèrement SHORT sur ETH et SOL',
  '',
  'Le régime NEUTRAL plaide pour éviter tout positionnement.',
].join('\n')

describe('withoutRecommendation', () => {
  it('drops the « Biais recommandé » section and everything under it', () => {
    const out = withoutRecommendation(REPORT)
    expect(out).not.toMatch(/biais recommandé/i)
    expect(out).not.toContain('SHORT sur ETH')
    expect(out).not.toContain('positionnement')
  })

  it('keeps the three sections before it, untouched', () => {
    const out = withoutRecommendation(REPORT)
    expect(out).toContain('## 1. Contexte macro global')
    expect(out).toContain('## 3. Risques à surveiller')
    expect(out).toContain('Le hack Bitget est le risque dominant.')
  })

  it('is a no-op on a report without that section', () => {
    const md = '## 1. Contexte\n\nRien à signaler.\n'
    expect(withoutRecommendation(md)).toBe(md)
  })

  it('matches the heading whatever its number, case or accent', () => {
    const md = '## A\n\ntexte\n\n### 5. BIAIS RECOMMANDE\n\nSHORT\n'
    const out = withoutRecommendation(md)
    expect(out).toContain('texte')
    expect(out).not.toContain('SHORT')
  })

  it('stops at the next heading of the same level when the section is not last', () => {
    const md = '## 4. Biais recommandé\n\nSHORT\n\n## 5. Calendrier\n\nISM le 01/10.\n'
    const out = withoutRecommendation(md)
    expect(out).not.toContain('SHORT')
    expect(out).toContain('ISM le 01/10.')
  })
})

// Lot 7 of the design audit (2026-09-25) left two « NEUTRAL » in the served text
// of /intelligence, both inside the generated report: the generator writes the
// machine enum (« Régime : NEUTRAL »). Translated at render time with the same
// maps the rest of the site uses (regime-labels.ts), whole upper-case words only.
describe('withFrenchRegimes', () => {
  it('turns the upper-case regime enums of the generated report into the French words of the site', () => {
    const md = 'Régime : NEUTRAL, tendance BULL, sentiment EXTREME_FEAR, feu RED.'
    expect(withFrenchRegimes(md)).toBe('Régime : neutre, tendance haussière, sentiment peur extrême, feu stress.')
  })

  it('leaves tickers, prose and lower-case words alone', () => {
    const md = 'BTC et ETH : le fear and greed reste à 42, le bull run est loin. Neutral en anglais.'
    expect(withFrenchRegimes(md)).toBe(md)
  })

  it('does not read FEAR inside EXTREME_FEAR twice', () => {
    expect(withFrenchRegimes('EXTREME_FEAR')).toBe('peur extrême')
  })
})
